### PR TITLE
chore: add debug mode for main process

### PR DESCRIPTION
**Pull request by CallanBi**
添加主进程 VSCode debug 支持。 / Support VSCode debug mode for the main process.

```bash
npm run debug
```
之后进入 VSCode debug 模式即可调试: [Debugging](https://code.visualstudio.com/docs/editor/debugging) / Then start debugging in VSCode: [Debugging](https://code.visualstudio.com/docs/editor/debugging)

### CODE REVIEW

**Comment by caoxiemeihao** [comment]
Thanks 😄

**Comment by Hacksore** [comment]
@CallanBi What is the launch config `Main(inspector)` for?

I was able to use `npm run debug` && `Main(vite)` to debug the main process sucessfully 🥳.
image

**Comment by CallanBi** [comment]
@Hacksore 
Technically there's no difference if you use VSCode to debug.
The only difference is that the `Main(inspector)` option provides a port, namely `9222` for the Chrome remote inspector, in which you can debug the program. This is because I inject a port exposure to the runtime in the `lanuch.json` file:
```JSON
      "runtimeArgs": [
        "--remote-debugging-port=9222",
        "${workspaceFolder}/dist/main/index.cjs",
      ],
```
image

You can just use `Main(vite)` if you don't want to use Chrome remote inspector.

**Comment by vanxv** [comment]
> Thanks 😄

通过一下合并呗。

**Pull request merged**
